### ISSUE TITLE
can't login FUTU OpenD

### ISSUE THREAD

**Issue by cometta** [MoomooOpen/py-moomoo-api#6]
i get error login failed. may i know does account need to be whitelisted to access FUTU OpenD ?

**Comment by devout-zliu** [comment]
> i get error login failed. may i know does account need to be whitelisted to access FUTU OpenD ?

Here we need more specific information to determine where the problem is. Please provide the display information when the login fails. If convenient, you can also provide the log file with the .ftlog suffix. The log path is as follows:
Windows: %appdata%/com.moomoo.OpenD/Log
Non-Windows: ~/.com.moomoo.OpenD/Log
